In [71]:
import pandas as pd
from  sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [72]:
d={'product':['kiki','oooo','pppp','pppp','kiki','kiki','oooo','oooo','oooo','oooo'],
   'tpyes':['maggi','yeepi','maggi','maggi','maggi','yeepi','dosa','dosa','maggi','dosa'],
   'target':[100,200,300,400,500,600,600,700,800,900]}

In [73]:
df=pd.DataFrame(d)
df

  product  tpyes  target
0    kiki  maggi     100
1    oooo  yeepi     200
2    pppp  maggi     300
3    pppp  maggi     400
4    kiki  maggi     500
5    kiki  yeepi     600
6    oooo   dosa     600
7    oooo   dosa     700
8    oooo  maggi     800
9    oooo   dosa     900

In [74]:
x=df.drop(columns='target')
y=df['target']

In [75]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [76]:
xtrain

  product  tpyes
5    kiki  yeepi
0    kiki  maggi
7    oooo   dosa
2    pppp  maggi
9    oooo   dosa
4    kiki  maggi
3    pppp  maggi
6    oooo   dosa

In [77]:
encoder=OrdinalEncoder()
encoder.fit_transform(xtrain)

array([[0., 2.],
       [0., 1.],
       [1., 0.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [2., 1.],
       [1., 0.]])

In [78]:
df['product'].unique

<bound method Series.unique of 0    kiki
1    oooo
2    pppp
3    pppp
4    kiki
5    kiki
6    oooo
7    oooo
8    oooo
9    oooo
Name: product, dtype: str>

In [79]:
'''encoder=OrdinalEncoder(categories=[['kiki','oooo']])
encoder.fit_transform(xtrain[['product']])

ValueError: Found unknown categories ['pppp'] in column 0 during fit
'''

"encoder=OrdinalEncoder(categories=[['kiki','oooo']])\nencoder.fit_transform(xtrain[['product']])\n\nValueError: Found unknown categories ['pppp'] in column 0 during fit\n"

In [80]:
'''encoder=OrdinalEncoder(categories=[['kiki','oooo','pppp']])
encoder.fit_transform(xtrain['product'])

ValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead.
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead'''

"encoder=OrdinalEncoder(categories=[['kiki','oooo','pppp']])\nencoder.fit_transform(xtrain['product'])\n\nValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead.\nPass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead"

In [82]:
encoder=OrdinalEncoder(categories=[['kiki','oooo','pppp']])#we have three uniqe value in this columns
encoder.fit_transform(xtrain[['product']])#kiki,oooo,pppp

array([[0.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.]])

In [83]:
df['tpyes'].unique

<bound method Series.unique of 0    maggi
1    yeepi
2    maggi
3    maggi
4    maggi
5    yeepi
6     dosa
7     dosa
8    maggi
9     dosa
Name: tpyes, dtype: str>

In [85]:
'''encoder=OrdinalEncoder(categories=[['kiki','oooo','pppp'],['yeepi','maggi','dosa']])
encoder.fit_transform(xtrain[['product']])

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).'''

"encoder=OrdinalEncoder(categories=[['kiki','oooo','pppp'],['yeepi','maggi','dosa']])\nencoder.fit_transform(xtrain[['product']])\n\nValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,)."

In [94]:
encoder=OrdinalEncoder(categories=[['kiki','pppp'],['yeepi','maggi','dosa']],handle_unknown='use_encoded_value',unknown_value=-1)
encoder.fit_transform(xtrain[['product','tpyes']])

array([[ 0.,  0.],
       [ 0.,  1.],
       [-1.,  2.],
       [ 1.,  1.],
       [-1.,  2.],
       [ 0.,  1.],
       [ 1.,  1.],
       [-1.,  2.]])

In [95]:
encoder.transform(xtest)

array([[-1.,  1.],
       [-1.,  0.]])

In [93]:
xtest

  product  tpyes
8    oooo  maggi
1    oooo  yeepi