In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [2]:
d={'product':['kiki','oooo','pppp','pppp','kiki','kiki','oooo','oooo','oooo','oooo'],
   'tpyes':['maggi','yeepi','maggi','maggi','maggi','yeepi','dosa','dosa','maggi','dosa'],
   'target':[100,200,300,400,500,600,600,700,800,900]}

In [3]:
df=pd.DataFrame(d)

In [4]:
x=df.drop(columns='target')
y=df['target']

In [5]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [6]:
xtrain

  product  tpyes
5    kiki  yeepi
0    kiki  maggi
7    oooo   dosa
2    pppp  maggi
9    oooo   dosa
4    kiki  maggi
3    pppp  maggi
6    oooo   dosa

In [7]:
enncoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
enncoder.fit_transform(xtrain)

array([[1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.]])

In [8]:
'''enncoder.transform(xtest[['product']])

ValueError: The feature names should match those that were passed during fit.'''

"enncoder.transform(xtest[['product']])\n\nValueError: The feature names should match those that were passed during fit."

In [9]:
enncoder.transform(xtest)

array([[0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.]])

In [10]:
enncoder.get_feature_names_out()#used to get the column names

array(['product_kiki', 'product_oooo', 'product_pppp', 'tpyes_dosa',
       'tpyes_maggi', 'tpyes_yeepi'], dtype=object)

In [11]:
new_input=pd.DataFrame({
    'product': ['r'],
    'tpyes': ['b6']
})
new_input

  product tpyes
0       r    b6

In [12]:
encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
encoder.fit_transform(xtrain)

array([[1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.]])

In [13]:
encoder.transform(xtest)

array([[0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.]])

In [14]:
encoder.transform(new_input)

array([[0., 0., 0., 0., 0., 0.]])